fix healthcheck

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -140,16 +140,22 @@ jobs:
             
             # Wait for container to become healthy
             echo "Waiting for container health check..."
-            for i in "\`seq 1 30\`"; do 
+            for i in `seq 1 30`; do 
               if [ "$(docker inspect --format='{{.State.Health.Status}}' ${{ env.REPOSITORY }})" = "healthy" ]; then
                 echo "Container is healthy"
-                exit 0
+                break
               fi
               echo -n "."
               sleep 1
             done
             
-            echo "Container failed health check"
-            docker logs ${{ env.REPOSITORY }}
-            exit 1
+            # Check if the container is healthy after the loop
+            if [ "$(docker inspect --format='{{.State.Health.Status}}' ${{ env.REPOSITORY }})" = "healthy" ]; then
+              echo "Container is healthy"
+              exit 0 
+            else
+              echo "Container failed health check"
+              docker logs ${{ env.REPOSITORY }}
+              exit 1
+            fi
           EOF
